import BookmarkedImg1 from "../../Assets/Images/bookmarked-img2.png";
import BookmarkedImg2 from "../../Assets/Images/bookmarked-img2.png";
import BookmarkedImg3 from "../../Assets/Images/bookmarked-img3.png";
import BookmarkedImg4 from "../../Assets/Images/bookmarked-img4.png";
export const bookmarkListData = [
  {
    id: "1",
    img: BookmarkedImg1,
    title: "Handling and lowering the Boot Up Process: Spot Termination Issue in ACE RTB Servers",
    date: "26 Nov 22",
    articleType: "Hard Problem",
    articleIcon: "hard-problem",
    technology: "Apache Kafka",
    author: "Rahul",
    impact: "MEDIUM IMPACT",
  },
  {
    id: "2",
    img: BookmarkedImg2,
    title: "Handling and lowering the Boot Up Process: Spot Termination Issue in ACE RTB Servers",
    date: "26 Nov 22",
    articleType: "BLOGS & TL ARTICLES",
    articleIcon: "blogs-at-articles",
    technology: "Apache Kafka",
    author: "Rahul",
    impact: "HIGH IMPACT",
  },
  {
    id: "3",
    img: BookmarkedImg3,
    title: "Handling and lowering the Boot Up Process: Spot Termination Issue in ACE RTB Servers",
    date: "26 Nov 22",
    articleType: "BLOGS & TL ARTICLES",
    articleIcon: "blogs-at-articles",
    technology: "Apache Kafka",
    author: "Rahul",
    impact: "HIGH IMPACT",
  },
  {
    id: "4",
    img: BookmarkedImg4,
    title: "Handling and lowering the Boot Up Process: Spot Termination Issue in ACE RTB Servers",
    date: "26 Nov 22",
    articleType: "Hard Problem",
    articleIcon: "hard-problem",
    technology: "Apache Kafka",
    author: "Rahul",
    impact: "MEDIUM IMPACT",
  },
  {
    id: "5",
    img: BookmarkedImg1,
    title: "Handling and lowering the Boot Up Process: Spot Termination Issue in ACE RTB Servers",
    date: "26 Nov 22",
    articleType: "BLOGS & TL ARTICLES",
    articleIcon: "blogs-at-articles",
    technology: "Apache Kafka",
    author: "Rahul",
    impact: "LOW IMPACT",
  },
];
