// DONOT MODIFY THIS FILE GENERATED BY YARN

import * as React from "react";

const iconList = ["wishlist", "eye"];

export interface IconProps {
  color?: string;
  className?: string;
  height?: number;
  kind?: string | any;
  onClick?: () => void;
  preview?: boolean;
  size?: number;
  style?: any;
  width?: number;
  wrapperStyle?: any;
}
export default class Icon extends React.Component<IconProps, {}> {
  static defaultProps = {
    className: "",
    color: "currentColor",
    size: 32,
  };

  render() {
    const { kind, preview } = this.props;
    return preview ? this.renderPreview() : this.renderIcon(kind);
  }

  renderPreview() {
    return (
      <div className="w-auto flex flex-wrap">
        {iconList.map((kind) => this.renderPreviewKind(kind))}
      </div>
    );
  }

  renderIcon(kind: string) {
    const { wrapperStyle } = this.props;
    if (wrapperStyle) {
      return <div style={wrapperStyle}>{this.getIcon(kind)}</div>;
    }
    return this.getIcon(kind);
  }

  renderPreviewKind(kind: string) {
    return (
      <div key={kind} className="w-1/4 px-2">
        <div className="p-4 my-2 bg-purple-100 text-purple-700 text-center rounded">
          <p className="mb-3 flex justify-center">{this.renderIcon(kind)}</p>
          <p>
            <small>&lt;Icon kind="{kind}" /&gt;</small>
          </p>
        </div>
      </div>
    );
  }

  getIcon(kind: string) {
    const {
      color,
      height,
      onClick,
      size,
      style,
      width,
      className,
      ...rest
    } = this.props;

    switch (kind) {
      case "wishlist":
        return (
          <svg
            {...rest}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              d="M12,21.35L10.55,20.03C5.4,15.36 2,12.27 2,8.5C2,5.41 4.42,3 7.5,3C9.24,3 10.91,3.81 12,5.08C13.09,3.81 14.76,3 16.5,3C19.58,3 22,5.41 22,8.5C22,12.27 18.6,15.36 13.45,20.03L12,21.35Z"
            />
          </svg>
        );
      case "eye":
        return (
          <svg
            {...rest}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            fill={color}
            viewBox="0 0 24 24"
          >
            <path
              fillRule="evenodd"
              d="M12,9A3,3 0 0,0 9,12A3,3 0 0,0 12,15A3,3 0 0,0 15,12A3,3 0 0,0 12,9M12,17A5,5 0 0,1 7,12A5,5 0 0,1 12,7A5,5 0 0,1 17,12A5,5 0 0,1 12,17M12,4.5C7,4.5 2.73,7.61 1,12C2.73,16.39 7,19.5 12,19.5C17,19.5 21.27,16.39 23,12C21.27,7.61 17,4.5 12,4.5Z"
            />
          </svg>
        );

      default:
        return null;
    }
  }
}
